version: '3'
services:

    rp:
        image: api-rp
        container_name: api_rp
        build: ./rp
        command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml

    app:
        image: api-app
        build: ./app
        ports:
            - 80
        labels:
            - "traefik.backend=api"
            - "traefik.frontend.rule=Host:api.delineate.io"
