version: 2
jobs:
  provision:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      # - run: bash ./agent/do_install.sh "1.7.1"
      - run: mkdir -p state
      - run: bash ./agent/hashicorp_install.sh "packer" "1.1.3"
      - run: cd ops/provision && ./provision.sh
      - run: echo $(ops/provision/get_image_id.sh) >> state/echo.txt
      # - run: cd ops/deploy && ./deploy.sh
      # - run: cd ops/destroy && ./destroy.sh
      - persist_to_workspace:
          root: state
          paths:
            - echo.txt
          
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: state
      - run: bash ./agent/hashicorp_install.sh "terraform" "0.11.2"
      - run: echo $(cat state/echo.txt)

  destroy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: bash ./agent/hashicorp_install.sh "terraform" "0.11.2"
      - run: echo "destroy the test environment"  


workflows:
  version: 2
  test:
    jobs:
      - provision
      - deploy
      - destroy