version: 2
jobs:
  provision:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: mkdir -p state
      # - run: bash agent/hashicorp_install.sh "packer" "1.1.3"
      # - run: cd ops/provision && ./provision.sh
      - run: bash ops/provision/get_image_id.sh
      - run: mv ops/provision/image_id.txt state/image_id.txt
      - persist_to_workspace:
          root: state
          paths:
            - image_id.txt
          
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: state
      - run: echo "$(cat state/image_id.txt)"
      - run: bash agent/hashicorp_install.sh "terraform" "0.11.2"
      - run: bash ops/deploy/deploy.sh "$(cat state/image_id.txt)"
      
  destroy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: state
      - run: bash agent/hashicorp_install.sh "terraform" "0.11.2"
      - run: bash ops/deploy/destroy.sh "$(cat state/image_id.txt)"


workflows:
  version: 2
  pipeline:
    jobs:
      - provision
      - deploy:
          requires:
            - provision
      - approval:
          type: approval
          requires:
           - deploy
      - destroy:
          requires:
            - approval