version: 2
jobs:

  clean:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: echo "Clean up placeholder here"

  validate:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: echo "Pure syntax validation"

  build_images:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: echo "Build images placeholder here"


  provision_master:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: bash ops/scripts/hashicorp_install.sh "packer" "1.1.3"
      - run: cd ops/provision && ./provision.sh "master"


  provision_node:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: mkdir -p state
      - run: bash ops/scripts/hashicorp_install.sh "packer" "1.1.3"
      - run: cd ops/provision && ./provision.sh "node"
      - run: bash ops/provision/get_image_id.sh "node"
      - run: mv ops/provision/node/node_image_id.txt state/node_image_id.txt
      - persist_to_workspace:
          root: state
          paths:
            - node_image_id.txt


  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: state
      - run: echo "$(cat state/node_image_id.txt)"
      - run: bash ops/scripts/hashicorp_install.sh "terraform" "0.11.2"
      - run: bash ops/deploy/deploy.sh "$(cat state/node_image_id.txt)"
      - run: mv ops/deploy/terraform.tfstate state/terraform.tfstate
      - persist_to_workspace:
          root: state
          paths:
            - terraform.tfstate


  test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: echo "testing here!"

  destroy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: state
      - run: bash ops/scripts/hashicorp_install.sh "terraform" "0.11.2"
      - run: bash ops/scripts/do_install.sh "1.7.1"
      - run: mv state/terraform.tfstate ops/deploy/terraform.tfstate
      - run: bash ops/deploy/destroy.sh "$(cat state/image_id.txt)"


workflows:
  version: 2
  pipeline:
    jobs:
      - clean
      - validate
      - build_images:
          requires:
            - clean
            - validation
      - provision_master:
          requires:
            - clean
            - validate
      - provision_node:
          requires:
            - clean
            - validate
      - deploy:
          requires:
            - build_images
            - provision_master
            - provision_node
      - test:
          requires:
              - deploy
      - destroy_approval:
          type: approval
          requires:
           - test
      - destroy:
          requires:
            - destroy_approval
            