version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    pre: 
      - run: sudo apt-get install -y tree

    steps:
      - checkout
      - run: bash ./agent/do_install.sh "1.7.1"
      - run: bash ./agent/hashicorp_install.sh "packer" "1.1.3"
      - run: bash ./agent/hashicorp_install.sh "terraform" "0.11.2"
      - run: cd ops/provision && ./provision.sh
      - run: cd ops/deploy && ./deploy.sh
      