version: 2
jobs:
  provision:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: bash ./agent/do_install.sh "1.7.1"
      - run: bash ./agent/hashicorp_install.sh "packer" "1.1.3"
      - run: bash ./agent/hashicorp_install.sh "terraform" "0.11.2"
      - run: cd ops/provision && ./provision.sh
      - run: cd ops/deploy && ./deploy.sh
      - run: cd ops/destroy && ./destroy.sh
  
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"  

  destroy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"  


workflows:
  version: 2
  test:
    jobs:
      - provision
      - deploy
          requires:
            - provision
      - build
          requires:
            - deploy
      - destroy
          requires:
            - build
